name: CICD

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Run composer install
        run: composer install -n --prefer-dist
      - name: Run tests
        run: ./vendor/bin/phpunit
